language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      before_install: 
        - sudo apt-get install network-manager
        - python3 setup.py install
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 setup.py install
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: 
        - choco install python
        - python setup.py install
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: 
  - pip3 install pylint coveralls
script: 
  - pylint -rn --errors-only ./magic
  - coverage run --source magic -m pytest
  - coveralls
